# Generated by Django 5.0.2 on 2024-02-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Training', '0002_uploadedfile_author_uploadedfile_filename_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
